package persistencia;
// Generated 08-10-2018 10:34:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Acceso generated by hbm2java
 */
public class Acceso  implements java.io.Serializable {


     private Integer idAcceso;
     private Empresa empresa;
     private String nombreAcceso;
     private String apellidoAcceso;
     private String usuario;
     private String contrasena;
     private String email;
     private String tipoAcceso;
     private String fechaRegistroAcceso;
     private Set configuracions = new HashSet(0);

    public Acceso() {
    }

	
    public Acceso(Empresa empresa) {
        this.empresa = empresa;
    }
    public Acceso(Empresa empresa, String nombreAcceso, String apellidoAcceso, String usuario, String contrasena, String email, String tipoAcceso, String fechaRegistroAcceso, Set configuracions) {
       this.empresa = empresa;
       this.nombreAcceso = nombreAcceso;
       this.apellidoAcceso = apellidoAcceso;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.email = email;
       this.tipoAcceso = tipoAcceso;
       this.fechaRegistroAcceso = fechaRegistroAcceso;
       this.configuracions = configuracions;
    }
   
    public Integer getIdAcceso() {
        return this.idAcceso;
    }
    
    public void setIdAcceso(Integer idAcceso) {
        this.idAcceso = idAcceso;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNombreAcceso() {
        return this.nombreAcceso;
    }
    
    public void setNombreAcceso(String nombreAcceso) {
        this.nombreAcceso = nombreAcceso;
    }
    public String getApellidoAcceso() {
        return this.apellidoAcceso;
    }
    
    public void setApellidoAcceso(String apellidoAcceso) {
        this.apellidoAcceso = apellidoAcceso;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTipoAcceso() {
        return this.tipoAcceso;
    }
    
    public void setTipoAcceso(String tipoAcceso) {
        this.tipoAcceso = tipoAcceso;
    }
    public String getFechaRegistroAcceso() {
        return this.fechaRegistroAcceso;
    }
    
    public void setFechaRegistroAcceso(String fechaRegistroAcceso) {
        this.fechaRegistroAcceso = fechaRegistroAcceso;
    }
    public Set getConfiguracions() {
        return this.configuracions;
    }
    
    public void setConfiguracions(Set configuracions) {
        this.configuracions = configuracions;
    }




}


