package persistencia;
// Generated 08-10-2018 10:34:34 AM by Hibernate Tools 4.3.1



/**
 * Compras generated by hbm2java
 */
public class Compras  implements java.io.Serializable {


     private Integer idCompra;
     private Contactos contactos;
     private Inventario inventario;
     private Iva iva;
     private Productos productos;
     private String fechaCompra;
     private Double totalCompra;

    public Compras() {
    }

	
    public Compras(Contactos contactos, Inventario inventario, Iva iva, Productos productos) {
        this.contactos = contactos;
        this.inventario = inventario;
        this.iva = iva;
        this.productos = productos;
    }
    public Compras(Contactos contactos, Inventario inventario, Iva iva, Productos productos, String fechaCompra, Double totalCompra) {
       this.contactos = contactos;
       this.inventario = inventario;
       this.iva = iva;
       this.productos = productos;
       this.fechaCompra = fechaCompra;
       this.totalCompra = totalCompra;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public Contactos getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Contactos contactos) {
        this.contactos = contactos;
    }
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }
    public Iva getIva() {
        return this.iva;
    }
    
    public void setIva(Iva iva) {
        this.iva = iva;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public String getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(String fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public Double getTotalCompra() {
        return this.totalCompra;
    }
    
    public void setTotalCompra(Double totalCompra) {
        this.totalCompra = totalCompra;
    }




}


