package persistencia;
// Generated 08-10-2018 10:34:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Configuracion generated by hbm2java
 */
public class Configuracion  implements java.io.Serializable {


     private Integer idConfiguracion;
     private Acceso acceso;
     private Empresa empresa;
     private byte[] logo;
     private String simboloMoneda;
     private String nombreMoneda;
     private String codigoMoneda;
     private Double iva;
     private String zonaHoraria;
     private Set facturaDetalles = new HashSet(0);

    public Configuracion() {
    }

	
    public Configuracion(Acceso acceso, Empresa empresa) {
        this.acceso = acceso;
        this.empresa = empresa;
    }
    public Configuracion(Acceso acceso, Empresa empresa, byte[] logo, String simboloMoneda, String nombreMoneda, String codigoMoneda, Double iva, String zonaHoraria, Set facturaDetalles) {
       this.acceso = acceso;
       this.empresa = empresa;
       this.logo = logo;
       this.simboloMoneda = simboloMoneda;
       this.nombreMoneda = nombreMoneda;
       this.codigoMoneda = codigoMoneda;
       this.iva = iva;
       this.zonaHoraria = zonaHoraria;
       this.facturaDetalles = facturaDetalles;
    }
   
    public Integer getIdConfiguracion() {
        return this.idConfiguracion;
    }
    
    public void setIdConfiguracion(Integer idConfiguracion) {
        this.idConfiguracion = idConfiguracion;
    }
    public Acceso getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(Acceso acceso) {
        this.acceso = acceso;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }
    public String getSimboloMoneda() {
        return this.simboloMoneda;
    }
    
    public void setSimboloMoneda(String simboloMoneda) {
        this.simboloMoneda = simboloMoneda;
    }
    public String getNombreMoneda() {
        return this.nombreMoneda;
    }
    
    public void setNombreMoneda(String nombreMoneda) {
        this.nombreMoneda = nombreMoneda;
    }
    public String getCodigoMoneda() {
        return this.codigoMoneda;
    }
    
    public void setCodigoMoneda(String codigoMoneda) {
        this.codigoMoneda = codigoMoneda;
    }
    public Double getIva() {
        return this.iva;
    }
    
    public void setIva(Double iva) {
        this.iva = iva;
    }
    public String getZonaHoraria() {
        return this.zonaHoraria;
    }
    
    public void setZonaHoraria(String zonaHoraria) {
        this.zonaHoraria = zonaHoraria;
    }
    public Set getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }




}


