package persistencia;
// Generated 08-10-2018 10:34:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer idEmpresa;
     private String nombreEmpresa;
     private String ncr;
     private String nit;
     private String direccionEmpresa;
     private String telefonoEmpresa;
     private String encargadoEmpresa;
     private String emailEmpresa;
     private Set facturaEncabezados = new HashSet(0);
     private Set accesos = new HashSet(0);
     private Set configuracions = new HashSet(0);

    public Empresa() {
    }

    public Empresa(String nombreEmpresa, String ncr, String nit, String direccionEmpresa, String telefonoEmpresa, String encargadoEmpresa, String emailEmpresa, Set facturaEncabezados, Set accesos, Set configuracions) {
       this.nombreEmpresa = nombreEmpresa;
       this.ncr = ncr;
       this.nit = nit;
       this.direccionEmpresa = direccionEmpresa;
       this.telefonoEmpresa = telefonoEmpresa;
       this.encargadoEmpresa = encargadoEmpresa;
       this.emailEmpresa = emailEmpresa;
       this.facturaEncabezados = facturaEncabezados;
       this.accesos = accesos;
       this.configuracions = configuracions;
    }
   
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getNcr() {
        return this.ncr;
    }
    
    public void setNcr(String ncr) {
        this.ncr = ncr;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getDireccionEmpresa() {
        return this.direccionEmpresa;
    }
    
    public void setDireccionEmpresa(String direccionEmpresa) {
        this.direccionEmpresa = direccionEmpresa;
    }
    public String getTelefonoEmpresa() {
        return this.telefonoEmpresa;
    }
    
    public void setTelefonoEmpresa(String telefonoEmpresa) {
        this.telefonoEmpresa = telefonoEmpresa;
    }
    public String getEncargadoEmpresa() {
        return this.encargadoEmpresa;
    }
    
    public void setEncargadoEmpresa(String encargadoEmpresa) {
        this.encargadoEmpresa = encargadoEmpresa;
    }
    public String getEmailEmpresa() {
        return this.emailEmpresa;
    }
    
    public void setEmailEmpresa(String emailEmpresa) {
        this.emailEmpresa = emailEmpresa;
    }
    public Set getFacturaEncabezados() {
        return this.facturaEncabezados;
    }
    
    public void setFacturaEncabezados(Set facturaEncabezados) {
        this.facturaEncabezados = facturaEncabezados;
    }
    public Set getAccesos() {
        return this.accesos;
    }
    
    public void setAccesos(Set accesos) {
        this.accesos = accesos;
    }
    public Set getConfiguracions() {
        return this.configuracions;
    }
    
    public void setConfiguracions(Set configuracions) {
        this.configuracions = configuracions;
    }




}


