package persistencia;
// Generated 08-10-2018 10:34:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fabricantes generated by hbm2java
 */
public class Fabricantes  implements java.io.Serializable {


     private Integer idFabricante;
     private String nombreFabricante;
     private Integer numeroProductos;
     private String descripcionFabricante;
     private String fechaRegistroFabricante;
     private Set productoses = new HashSet(0);

    public Fabricantes() {
    }

    public Fabricantes(String nombreFabricante, Integer numeroProductos, String descripcionFabricante, String fechaRegistroFabricante, Set productoses) {
       this.nombreFabricante = nombreFabricante;
       this.numeroProductos = numeroProductos;
       this.descripcionFabricante = descripcionFabricante;
       this.fechaRegistroFabricante = fechaRegistroFabricante;
       this.productoses = productoses;
    }
   
    public Integer getIdFabricante() {
        return this.idFabricante;
    }
    
    public void setIdFabricante(Integer idFabricante) {
        this.idFabricante = idFabricante;
    }
    public String getNombreFabricante() {
        return this.nombreFabricante;
    }
    
    public void setNombreFabricante(String nombreFabricante) {
        this.nombreFabricante = nombreFabricante;
    }
    public Integer getNumeroProductos() {
        return this.numeroProductos;
    }
    
    public void setNumeroProductos(Integer numeroProductos) {
        this.numeroProductos = numeroProductos;
    }
    public String getDescripcionFabricante() {
        return this.descripcionFabricante;
    }
    
    public void setDescripcionFabricante(String descripcionFabricante) {
        this.descripcionFabricante = descripcionFabricante;
    }
    public String getFechaRegistroFabricante() {
        return this.fechaRegistroFabricante;
    }
    
    public void setFechaRegistroFabricante(String fechaRegistroFabricante) {
        this.fechaRegistroFabricante = fechaRegistroFabricante;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


