package persistencia;
// Generated 08-10-2018 10:34:34 AM by Hibernate Tools 4.3.1



/**
 * FacturaDetalle generated by hbm2java
 */
public class FacturaDetalle  implements java.io.Serializable {


     private Integer idFacturaDetalle;
     private Configuracion configuracion;
     private FacturaEncabezado facturaEncabezado;
     private Iva iva;
     private Productos productos;
     private Integer cantidad;
     private Double totalFila;
     private Double totalColumna;
     private Double subtotalColumna;

    public FacturaDetalle() {
    }

	
    public FacturaDetalle(Configuracion configuracion, FacturaEncabezado facturaEncabezado, Iva iva, Productos productos) {
        this.configuracion = configuracion;
        this.facturaEncabezado = facturaEncabezado;
        this.iva = iva;
        this.productos = productos;
    }
    public FacturaDetalle(Configuracion configuracion, FacturaEncabezado facturaEncabezado, Iva iva, Productos productos, Integer cantidad, Double totalFila, Double totalColumna, Double subtotalColumna) {
       this.configuracion = configuracion;
       this.facturaEncabezado = facturaEncabezado;
       this.iva = iva;
       this.productos = productos;
       this.cantidad = cantidad;
       this.totalFila = totalFila;
       this.totalColumna = totalColumna;
       this.subtotalColumna = subtotalColumna;
    }
   
    public Integer getIdFacturaDetalle() {
        return this.idFacturaDetalle;
    }
    
    public void setIdFacturaDetalle(Integer idFacturaDetalle) {
        this.idFacturaDetalle = idFacturaDetalle;
    }
    public Configuracion getConfiguracion() {
        return this.configuracion;
    }
    
    public void setConfiguracion(Configuracion configuracion) {
        this.configuracion = configuracion;
    }
    public FacturaEncabezado getFacturaEncabezado() {
        return this.facturaEncabezado;
    }
    
    public void setFacturaEncabezado(FacturaEncabezado facturaEncabezado) {
        this.facturaEncabezado = facturaEncabezado;
    }
    public Iva getIva() {
        return this.iva;
    }
    
    public void setIva(Iva iva) {
        this.iva = iva;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getTotalFila() {
        return this.totalFila;
    }
    
    public void setTotalFila(Double totalFila) {
        this.totalFila = totalFila;
    }
    public Double getTotalColumna() {
        return this.totalColumna;
    }
    
    public void setTotalColumna(Double totalColumna) {
        this.totalColumna = totalColumna;
    }
    public Double getSubtotalColumna() {
        return this.subtotalColumna;
    }
    
    public void setSubtotalColumna(Double subtotalColumna) {
        this.subtotalColumna = subtotalColumna;
    }




}


