package persistencia;
// Generated 08-10-2018 10:34:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Iva generated by hbm2java
 */
public class Iva  implements java.io.Serializable {


     private Integer idIva;
     private Double ivaTasa;
     private Double ivaRetenido;
     private Double ivaPagado;
     private Double ivaTotal;
     private Set facturaDetalles = new HashSet(0);
     private Set comprases = new HashSet(0);

    public Iva() {
    }

    public Iva(Double ivaTasa, Double ivaRetenido, Double ivaPagado, Double ivaTotal, Set facturaDetalles, Set comprases) {
       this.ivaTasa = ivaTasa;
       this.ivaRetenido = ivaRetenido;
       this.ivaPagado = ivaPagado;
       this.ivaTotal = ivaTotal;
       this.facturaDetalles = facturaDetalles;
       this.comprases = comprases;
    }
   
    public Integer getIdIva() {
        return this.idIva;
    }
    
    public void setIdIva(Integer idIva) {
        this.idIva = idIva;
    }
    public Double getIvaTasa() {
        return this.ivaTasa;
    }
    
    public void setIvaTasa(Double ivaTasa) {
        this.ivaTasa = ivaTasa;
    }
    public Double getIvaRetenido() {
        return this.ivaRetenido;
    }
    
    public void setIvaRetenido(Double ivaRetenido) {
        this.ivaRetenido = ivaRetenido;
    }
    public Double getIvaPagado() {
        return this.ivaPagado;
    }
    
    public void setIvaPagado(Double ivaPagado) {
        this.ivaPagado = ivaPagado;
    }
    public Double getIvaTotal() {
        return this.ivaTotal;
    }
    
    public void setIvaTotal(Double ivaTotal) {
        this.ivaTotal = ivaTotal;
    }
    public Set getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }
    public Set getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set comprases) {
        this.comprases = comprases;
    }




}


