package persistencia;
// Generated 08-10-2018 10:34:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private Fabricantes fabricantes;
     private String nombreProducto;
     private Double precioUnitario;
     private String descripcionProducto;
     private String modelo;
     private Set inventarios = new HashSet(0);
     private Set facturaDetalles = new HashSet(0);
     private Set comprases = new HashSet(0);

    public Productos() {
    }

	
    public Productos(Fabricantes fabricantes) {
        this.fabricantes = fabricantes;
    }
    public Productos(Fabricantes fabricantes, String nombreProducto, Double precioUnitario, String descripcionProducto, String modelo, Set inventarios, Set facturaDetalles, Set comprases) {
       this.fabricantes = fabricantes;
       this.nombreProducto = nombreProducto;
       this.precioUnitario = precioUnitario;
       this.descripcionProducto = descripcionProducto;
       this.modelo = modelo;
       this.inventarios = inventarios;
       this.facturaDetalles = facturaDetalles;
       this.comprases = comprases;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Fabricantes getFabricantes() {
        return this.fabricantes;
    }
    
    public void setFabricantes(Fabricantes fabricantes) {
        this.fabricantes = fabricantes;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public String getDescripcionProducto() {
        return this.descripcionProducto;
    }
    
    public void setDescripcionProducto(String descripcionProducto) {
        this.descripcionProducto = descripcionProducto;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }
    public Set getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }
    public Set getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set comprases) {
        this.comprases = comprases;
    }




}


